version: 2

sources:
  - name: raw_synchtank
    schema: public
    database: postgres
    loaded_at_field: _airbyte_emitted_at
    tables:
      - name: purchases
      - name: baskets
      - name: tracks
      - name: users
      - name: artists
      - name: genres
      - name: collections
      - name: baskets_basketitems
      - name: licenses
      - name: reviewtracks
      - name: reviewartists
      - name: reviewalbums


  - name: raw_stripe
    schema: public_stripe
    database: postgres
    tables:
      - name: charges
      - name: refunds
      - name: disputes

  - name: jobs
    schema: public_normalized
    database: postgres
    tables:
      - name: job_helloworks_contracts
      - name: job_detail
      - name: job_helloworks_tracker
      - name: job_payments
      - name: job_payouts
      - name: job_tracker
      - name: job_sales_reports




