version: 2

sources:
  - name: raw_synchtank
    schema: public
    database: postgres
    loaded_at_field: _airbyte_emitted_at
    tables:
      - name: purchases
      - name: baskets
      - name: tracks
      - name: users
      - name: artists
      - name: genres
      - name: collections
      - name: baskets_basketitems
      - name: licenses

  - name: raw_stripe
    schema: public_stripe
    database: postgres
    tables:
      - name: charges
      - name: refunds
      - name: disputes
  - name: jobs
    schema: public_normalized
    database: postgres
    tables:
      - name: job_helloworks_contracts


models:
  - name: normalized_tracks
    config:
      contract:
        enforced: true
    columns:
      - name: _airbyte_ab_id
        data_type: varchar
      - name: _airbyte_emitted_at
        data_type: timestamp with time zone
      - name: _airbyte_tracks_hashid
        data_type: text
      - name: album
        data_type: text
      - name: albumupc
        data_type: text
      - name: artist
        data_type: bigint
      - name: collections
        data_type: bigint
      - name: composer
        data_type: text
      - name: composition
        data_type: jsonb
      - name: compositionproduct
        data_type: jsonb
      - name: compositionproductiontracks
        data_type: jsonb
      - name: compositionpublishers
        data_type: jsonb
      - name: compositiontitle
        data_type: text
      - name: compositionwriters
        data_type: jsonb
      - name: compositionyear
        data_type: jsonb
      - name: created
        data_type: timestamp
      - name: customtrackid
        data_type: text
      - name: duration
        data_type: bigint
      - name: file_url
        data_type: text
      - name: filename
        data_type: text
      - name: genre_names
        data_type: jsonb
      - name: genres
        data_type: jsonb
      - name: id
        data_type: bigint
      - name: is_exclusive
        data_type: boolean
      - name: iscomposition
        data_type: boolean
      - name: isrc
        data_type: text
      - name: last_modified
        data_type: timestamp
      - name: licenses
        data_type: jsonb
      - name: originally_published
        data_type: timestamp
      - name: published
        data_type: timestamp
      - name: releasedate
        data_type: text
      - name: title
        data_type: text
        constraints:
          - type: not_null
      - name: youtubeassetids
        data_type: jsonb




